# Lab 10.01 : Convolutional layer - demo

In [1]:
import torch
import torch.nn as nn

### Make a convolutional module
* inputs:  2 channels
* output:  5 activation maps
* filters are 3x3
* padding with one layer of zero to not shrink anything

In [2]:
mod = nn.Conv2d(2 ,5 ,kernel_size=3, padding=1)

### Make an input 2 x 6 x 6  (two channels, each one has 6 x 6 pixels )

In [3]:
bs=1

x=torch.rand(bs,2,6,6)

print(x)

tensor([[[[0.2779, 0.6547, 0.5934, 0.9785, 0.1308, 0.1562],
          [0.2564, 0.1269, 0.5575, 0.6709, 0.1691, 0.4741],
          [0.0978, 0.4471, 0.6563, 0.2004, 0.9138, 0.8688],
          [0.1713, 0.3125, 0.0570, 0.6934, 0.4856, 0.1290],
          [0.0250, 0.5295, 0.4484, 0.9531, 0.2438, 0.5036],
          [0.4718, 0.1024, 0.1682, 0.2673, 0.8497, 0.3347]],

         [[0.6815, 0.0176, 0.9905, 0.9145, 0.0792, 0.8790],
          [0.6758, 0.6072, 0.9169, 0.1528, 0.8226, 0.9752],
          [0.9360, 0.1138, 0.2548, 0.4823, 0.4623, 0.2786],
          [0.2792, 0.9250, 0.5647, 0.2074, 0.5963, 0.2626],
          [0.7578, 0.9984, 0.4327, 0.1307, 0.2974, 0.7135],
          [0.6725, 0.5221, 0.8596, 0.9924, 0.5693, 0.8320]]]])


### Feed it to the convolutional layer: the output should have 5 channels (each one is 6x6)

In [4]:
y=mod(x)

print(y)

tensor([[[[-0.2086, -0.0849, -0.4725, -0.0816,  0.0314, -0.3547],
          [-0.3403, -0.4056, -0.4596,  0.0507, -0.3582, -0.0115],
          [-0.2657, -0.1700, -0.2712, -0.3018, -0.2753,  0.1900],
          [-0.1901, -0.4350, -0.4785, -0.2010, -0.2264, -0.1277],
          [-0.3588, -0.2251, -0.2195, -0.4004, -0.3658, -0.0869],
          [-0.1059,  0.1209, -0.0374, -0.1673, -0.0487,  0.0816]],

         [[-0.0316,  0.0029,  0.1498,  0.1520, -0.1501,  0.0789],
          [-0.0900,  0.3772,  0.1087,  0.1750,  0.1431, -0.0140],
          [ 0.0571,  0.2722,  0.2577,  0.3809,  0.1357,  0.3158],
          [-0.1848,  0.2776,  0.2701, -0.0791,  0.0603,  0.0684],
          [ 0.0024,  0.2582,  0.3235,  0.4193,  0.1053,  0.0607],
          [ 0.0426,  0.1774,  0.0375,  0.2599,  0.0388,  0.1522]],

         [[ 0.0991,  0.2580, -0.0195,  0.0888,  0.0765, -0.1088],
          [-0.3489, -0.0082, -0.1243, -0.1674,  0.1330, -0.0474],
          [ 0.0806, -0.1194, -0.2632,  0.1367, -0.0270, -0.3881],
      

### Lets look at the 5 filters.
* Our filters are 2x3x3
* Each of the filter has 2 channels because the inputs have two channels

In [5]:
mod.weight

Parameter containing:
tensor([[[[-0.0750, -0.1344, -0.1885],
          [ 0.0096,  0.0601, -0.1182],
          [ 0.0731, -0.0484, -0.1239]],

         [[ 0.1747,  0.0461, -0.1050],
          [ 0.0935, -0.1882,  0.0375],
          [-0.1752, -0.2158, -0.0069]]],


        [[[-0.1337,  0.1598, -0.0612],
          [ 0.0918,  0.1027,  0.1202],
          [-0.1239, -0.0706, -0.0067]],

         [[ 0.1763,  0.0164,  0.1753],
          [ 0.0702,  0.0887, -0.0974],
          [ 0.1887,  0.0538, -0.0478]]],


        [[[ 0.1410, -0.1653, -0.1896],
          [-0.1841, -0.1604,  0.1767],
          [ 0.1227,  0.1520,  0.1252]],

         [[-0.0864, -0.0560, -0.0312],
          [-0.0477, -0.1515, -0.0150],
          [ 0.1188, -0.1784,  0.2248]]],


        [[[ 0.1606, -0.0586,  0.0608],
          [ 0.0198, -0.0505,  0.1272],
          [ 0.1770, -0.1058,  0.2195]],

         [[ 0.1492,  0.0824,  0.1772],
          [ 0.0366, -0.0438,  0.1669],
          [-0.1085, -0.2226,  0.0494]]],


        [[[ 0.1920