# Introduction to PyTorch  

In [1]:
import torch

## Code examples

### Construct a vector of 3 elements

In [2]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


### Construct a  2 x 2 matrix

In [3]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [7]:
A=torch.rand(10,2)
print(A)

tensor([[0.8232, 0.9668],
        [0.5293, 0.3177],
        [0.2990, 0.1083],
        [0.4430, 0.7959],
        [0.9091, 0.5705],
        [0.0279, 0.0925],
        [0.9942, 0.4845],
        [0.9921, 0.0563],
        [0.9014, 0.3057],
        [0.9452, 0.7383]])


### Construct a 10 x 2 matrix filled with zeros

In [9]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor

In [13]:
B = torch.rand(5,2,2)
print(B)

tensor([[[0.7933, 0.5578],
         [0.8493, 0.0636]],

        [[0.6931, 0.2454],
         [0.8027, 0.4579]],

        [[0.2916, 0.4757],
         [0.6654, 0.6417]],

        [[0.9749, 0.3985],
         [0.5400, 0.1645]],

        [[0.2831, 0.7691],
         [0.5142, 0.6642]]])


In [14]:
B.size()

torch.Size([5, 2, 2])

In [15]:
B.dim()

3

### Size and Dimension of a Tensor

#### A 3-dimensional Tensor

In [ ]:
A=torch.rand(3,2,2)
print(A)

tensor([[[0.8826, 0.2284],
         [0.7530, 0.2435]],

        [[0.2213, 0.6198],
         [0.8820, 0.9255]],

        [[0.5898, 0.3268],
         [0.3918, 0.9752]]])


In [ ]:
print(  A.dim()   )

3


In [ ]:
print(  A.size()   )

torch.Size([3, 2, 2])


In [ ]:
print(  A.size(0)  )

3


#### A 2-dimensional Tensor

In [ ]:
B=torch.rand(3,5)
print(B)

tensor([[0.7671, 0.6470, 0.7702, 0.6315, 0.4696],
        [0.7422, 0.5464, 0.1165, 0.6252, 0.5320],
        [0.9052, 0.0902, 0.5475, 0.0883, 0.6006]])


In [ ]:
print( B.dim()  )

2


In [ ]:
print( B.size()  )

torch.Size([3, 5])


In [ ]:
print( B.size(0) )

3


In [ ]:
print( B.size(1) )

5


#### A 1-dimensional Tensor

In [ ]:
x=torch.rand(7)
print(x)

tensor([0.8747, 0.9436, 0.9673, 0.3596, 0.0489, 0.9237, 0.5866])


In [ ]:
print( x.dim() )

1


In [ ]:
print( x.size() )

torch.Size([7])


### Adding and multiplying tensors

In [ ]:
A=torch.rand(2,2)
B=torch.rand(2,2)

C=2*B
D=A+C
E=A*B

print(A)
print('')
print(B)
print('')
print(C)
print('')
print(C)
print('')
print(E)

tensor([[0.7513, 0.6579],
        [0.6255, 0.2182]])

tensor([[0.4870, 0.2859],
        [0.7319, 0.6777]])

tensor([[0.9740, 0.5718],
        [1.4638, 1.3553]])

tensor([[0.9740, 0.5718],
        [1.4638, 1.3553]])

tensor([[0.3659, 0.1881],
        [0.4578, 0.1479]])


### Floats versus integers

In [ ]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [ ]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [ ]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [ ]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other functions

In [ ]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [ ]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([5, 1, 7, 6, 0, 9, 3, 4, 8, 2])
torch.LongTensor


In [ ]:
x=torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


### Tips

Check tensor sizes for algebra computations like multiplication torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

### Reshaping a tensor

In [ ]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [ ]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [ ]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [ ]:
y=x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [ ]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [ ]:
print( y[0] )

tensor([0, 1])


In [ ]:
print( y[1] )

tensor([2, 3])


In [ ]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [ ]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [ ]:
print( y[1:4] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [ ]:
idx = 1
n=3

print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let check the sizes after slicing

In [ ]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [ ]:
z= y[1:1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]])

dimension= 2
torch.Size([3, 2])


In [ ]:
v=y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2, 3])

dimension= 1
torch.Size([2])


### Acessing the entries of a Tensor

In [ ]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [ ]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [ ]:
a=y[4,0]
print(a) # a is a scalar, not a tensor

tensor(8)


In [ ]:
print(a.dim())
print(a.size())

0
torch.Size([])


### A matrix is 2-dimensional Tensor
### A row of a matrix is a 1-dimensional Tensor
### An entry of a matrix is a 0-dimensional  Tensor

### 0-dimensional Tensor are scalar!

### If we want to convert a 0-dimensional Tensor into  python number, we need to use item()

In [ ]:
b=a.item()
print(a)
print(type(a))
print(b)
print(type(b))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>


## Exercises

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [18]:
# Write your code here
A = torch.Tensor([[1,2], [3,4]])
B = torch.Tensor([[10,20], [30,40]])

C = A + B
print(A)
print(B)
print(C)

tensor([[1., 2.],
        [3., 4.]])
tensor([[10., 20.],
        [30., 40.]])
tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [19]:
# Write your code here
print(A.dim())
print(A.size())
print(A.type())


2
torch.Size([2, 2])
torch.FloatTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [23]:
# Write your code here
A = A.long()
print(A.type())
print(A)

torch.LongTensor
tensor([[1, 2],
        [3, 4]])


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [25]:
# Write your code here
randomTensor = torch.rand(5,2,3)
print(randomTensor)
print(randomTensor.type())
print(randomTensor.dim())
print(randomTensor.size())
print(randomTensor.size(1))

tensor([[[0.8269, 0.1554, 0.0986],
         [0.7743, 0.2168, 0.1283]],

        [[0.1165, 0.0676, 0.8610],
         [0.0674, 0.9438, 0.7470]],

        [[0.1944, 0.0351, 0.1202],
         [0.2842, 0.6960, 0.4679]],

        [[0.1482, 0.8080, 0.0506],
         [0.6266, 0.8252, 0.8101]],

        [[0.8665, 0.6372, 0.5834],
         [0.9272, 0.2569, 0.6765]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [26]:
# Write your code here
AB = torch.zeros(2,3,4,5)
print(AB)


tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
